### ISSUE TITLE
Question regarding model evaluation

### ISSUE THREAD

**Issue by n-kubiak** [hhqweasd/LG-ShadowNet#2]
Hello,

I'm trying to reproduce the results reported in your paper. When you evaluate your performance using the provided ```evaluate.m``` script, which flag do you use - "ours = 1" (calculate RMSE values per image and then average across all images in the test dataset) or "ours = 0" (average across all pixels of the test set)? Also, the reported results are calculated on the full size images (640x480), right?

As far as I understand from the paper/your repo, you use "ours = 1" but I wanted to double check because the default settings in the eval script are set to "ours = 0" and the size is 256x256.

Thanks,
NK

**Comment by hhqweasd** [comment]
These parameters can be flexibly set.  Please check the parameters carefully to confirm that they meet your requirements.
